FROM ocaml/opam:alpine-ocaml-5.0

RUN opam install -y dune \
    alcotest \
    angstrom \
    base64 \
    js_of_ocaml \
    js_of_ocaml-ppx \
    ppx_deriving \
    ppx_deriving_yojson \
    promise_jsoo \
    re \
    xml-light \
    yojson
