name = "compose_news"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-07-28"
node_compat = true

main = "_build/default/bin/main.bc.js"

[build]
command = "make build_wrangler"
watch_dir = ["bin", "lib"]

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]
