name = "compose_news"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-12-27"
node_compat = true

main = "_build/default/bin/main.bc.js"

[build]
command = "make build"
watch_dir = "bin"

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]
